version: '3.1'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - local-net

  fastapi:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
